// Generated by CoffeeScript 1.6.3
(function() {
  var getFieldData, getReportData, renderReport;

  getFieldData = function(id) {
    return _.findWhere(serializedForm.fields, {
      id: id
    });
  };

  getReportData = function(id) {
    return _.find(Typeform.DataService.get('reports'), function(report) {
      return report.field.id === id;
    });
  };

  renderReport = function() {
    var $el, fieldData, id, reportData;
    $el = $(this);
    id = parseInt($el.data('field'), 10);
    fieldData = getFieldData(id);
    reportData = getReportData(id);
    if (fieldData.type === 'opinion-scale') {
      new App.Reports.OpinionScaleReport($el, fieldData, reportData);
    }
  };

  $('#report-questions > li').each(renderReport);

}).call(this);
