// Generated by CoffeeScript 1.6.3
/**
 * ==========================================================================
 *
 * Typeform.DataService : Service to parse document stored json data
 *
 * ==========================================================================
*/


(function() {
  var getContent, getFeatures, getJson, getTemplate, json_prefix, template_prefix;

  json_prefix = 'json_data-';

  template_prefix = 'tpl_data-';

  getContent = function(id) {
    return document.getElementById(id).innerHTML;
  };

  getJson = function(id) {
    var data;
    if (id == null) {
      id = false;
    }
    if (!id) {
      return {};
    }
    data = getContent(json_prefix + id);
    return JSON.parse(data);
  };

  getTemplate = function(id) {
    if (id == null) {
      id = false;
    }
    if (!id) {
      return '';
    }
    return getContent(template_prefix + id);
  };

  getFeatures = function() {
    return getJson('json_data-features');
  };

  namespace('tf.data.ext', function(exports) {
    exports.json = getJson;
    exports.tpl = getTemplate;
  });

  namespace('Typeform.DataService', function(exports) {
    exports.get = getJson;
    exports.json = getJson;
    exports.template = getTemplate;
  });

  namespace('Typeform.Features', function(exports) {
    exports.get = getFeatures;
  });

}).call(this);
