(function(g){var window=this;var GAa=function(a,b){return g.Vb(a,b)},g6=function(a){g.Im(a,"zx",g.xb());
return a},h6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Lm(a.g,b,c)},HAa=function(a,b){var c=[];
g.rk(b,function(a){try{var b=g.YC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.XC(b)&&c.push(a):c.push(a)},a);
return c},IAa=function(a,b){var c=HAa(a,b);
(0,g.B)(c,function(a){g.YC.prototype.remove.call(this,a)},a)},JAa=function(a,b,c,d){var e=new g.zm(null,void 0);
a&&g.Am(e,a);b&&g.Bm(e,b);c&&g.Cm(e,c);d&&g.Dm(e,d);return e},KAa=function(a){g.RF[a]&&(a=g.RF[a],(0,g.B)(a,function(a){g.PF[a]&&delete g.PF[a]}),a.length=0)},LAa=function(a){var b=g.OF();
if(b)if(b.clear(a),a)KAa(a);else for(var c in g.RF)KAa(c)},i6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.tm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",MAa(this,a.capabilities||""),NAa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},MAa=function(a,b){a.capabilities.clear();
(0,g.Jd)(b.split(","),g.Fa(GAa,OAa)).forEach(function(b){a.capabilities.add(b)})},NAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},j6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},k6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},PAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},QAa=function(a){return new j6(a)},RAa=function(a){return g.za(a)?(0,g.H)(a,QAa):[]},l6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},m6=function(a){return g.za(a)?"["+(0,g.H)(a,l6).join(",")+"]":"null"},n6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},SAa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},o6=function(a,b){return g.Ma(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},p6=function(a,b){return g.Ma(a,function(a){return k6(a,b)})},TAa=function(){var a=(0,g.KG)();
a&&IAa(a,a.g.Rd(!0))},q6=function(){var a=g.NG("yt-remote-connected-devices")||[];
g.ib(a);return a},UAa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},VAa=function(a){g.MG("yt-remote-connected-devices",a,86400)},s6=function(){if(r6)return r6;
var a=g.NG("yt-remote-device-id");a||(a=n6(),g.MG("yt-remote-device-id",a,31536E3));for(var b=q6(),c=1,d=a;g.C(b,d);)c++,d=a+"#"+c;return r6=d},t6=function(){var a=q6(),b=s6();
g.C(a,b);g.PG()&&g.kb(a,b);a=UAa(a);if(g.Qa(a))try{g.xG("remote_sid")}catch(c){}else try{g.wG("remote_sid",a.join(","),-1)}catch(c){}},WAa=function(){return g.NG("yt-remote-session-browser-channel")},XAa=function(){return g.NG("yt-remote-local-screens")||[]},YAa=function(){g.MG("yt-remote-lounge-token-expiration",!0,86400)},ZAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(XAa(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.im)(c,function(a){return!g.C(b,a)})&&YAa();
g.MG("yt-remote-local-screens",a,31536E3)},$Aa=function(a,b){g.MG("yt-remote-session-browser-channel",a);
g.MG("yt-remote-session-screen-id",b);var c=q6(),d=s6();g.C(c,d)||c.push(d);VAa(c);t6()},u6=function(a){a||(g.OG("yt-remote-session-screen-id"),g.OG("yt-remote-session-video-id"));
t6();a=q6();g.Ua(a,s6());VAa(a)},aBa=function(){if(!v6){var a=g.iD();
a&&(v6=new g.SC(a))}return v6?!!v6.get("yt-remote-use-staging-server"):!1},bBa=function(){var a=window.document.createElement("a");
g.Yc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},cBa=function(a,b){var c=g.Cd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Zc(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},dBa=function(){var a=bBa(),b=window.document.getElementById(a),c=b&&g.bF(b,"loaded");
c||b&&!c||(b=cBa(a,function(){g.bF(b,"loaded")||(g.aF(b,"loaded","true"),g.VF(a),g.RD(g.Fa(LAa,a),0))}))},w6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},eBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},x6=function(a){a.length?fBa(a.shift(),function(){x6(a)}):y6()},gBa=function(a){return"chrome-extension://"+a+z6},fBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},A6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},y6=function(){var a=eBa();
a&&a(!1,"No cast extension found")},B6=function(){if(hBa){var a=2,b=eBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;fBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",y6,c)}},iBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(B6(),a({command:"cast.sender.init"}))},jBa=function(){B6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);x6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+z6,"//www.gstatic.com/eureka/clank"+z6])},C6=function(a,b,c){g.L.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.dd=b;this.B=(0,g.z)(this.HI,this);this.g=!1;this.l=0;this.o=this.wa=null;this.A=[]},D6=function(){},E6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Pm(this);this.l=new g.sg;this.l.setInterval(250)},lBa=function(a,b,c){a.xj=1;
a.kh=g6(b.clone());a.Ji=c;a.C=!0;kBa(a,null)},F6=function(a,b,c,d,e){a.xj=1;
a.kh=g6(b.clone());a.Ji=null;a.C=c;e&&(a.WC=!1);kBa(a,d)},kBa=function(a,b){a.dk=(0,g.G)();
G6(a);a.Dh=a.kh.clone();h6(a.Dh,"t",a.D);a.gm=0;a.Rc=a.g.Jq(a.g.Wl()?b:null);0<a.qr&&(a.Yo=new g.Tk((0,g.z)(a.nE,a,a.Rc),a.qr));a.A.T(a.Rc,"readystatechange",a.QT);var c=a.ki?g.bc(a.ki):{};a.Ji?(a.Ip="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.Dh,a.Ip,a.Ji,c)):(a.Ip="GET",a.WC&&!g.yd&&(c.Connection="close"),a.Rc.send(a.Dh,a.Ip,null,c));a.g.qf(1)},oBa=function(a,b,c){for(var d=!0;!a.Uh&&a.gm<c.length;){var e=mBa(a,c);
if(e==H6){4==b&&(a.lh=4,I6(15),d=!1);break}else if(e==nBa){a.lh=4;I6(16);d=!1;break}else J6(a,e)}4==b&&0==c.length&&(a.lh=1,I6(17),d=!1);a.wf=a.wf&&d;d||(K6(a),L6(a))},mBa=function(a,b){var c=a.gm,d=b.indexOf("\n",c);
if(-1==d)return H6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return nBa;d+=1;if(d+c>b.length)return H6;var e=b.substr(d,c);a.gm=d+c;return e},qBa=function(a,b){a.dk=(0,g.G)();
G6(a);var c=b?window.location.hostname:"";a.Dh=a.kh.clone();g.Im(a.Dh,"DOMAIN",c);g.Im(a.Dh,"t",a.D);try{a.yf=new window.ActiveXObject("htmlfile")}catch(n){K6(a);a.lh=7;I6(22);L6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in M6)k=M6[l];else if(l in pBa)k=M6[l]=pBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=M6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.$c(g.vc("b/12014412"),d);a.yf.open();a.yf.write(g.Rc(c));a.yf.close();a.yf.parentWindow.m=(0,g.z)(a.WS,a);a.yf.parentWindow.d=(0,g.z)(a.jC,a,!0);a.yf.parentWindow.rpcClose=(0,g.z)(a.jC,a,!1);c=a.yf.createElement("DIV");a.yf.parentWindow.document.body.appendChild(c);d=g.Ic(a.Dh.toString());d=g.rb(g.Fc(d));d=g.$c(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Rc(d);
a.g.qf(1)},G6=function(a){a.ev=(0,g.G)()+a.B;
rBa(a,a.B)},rBa=function(a,b){if(null!=a.wk)throw Error("WatchDog timer not null");
a.wk=N6((0,g.z)(a.nT,a),b)},O6=function(a){a.wk&&(g.w.clearTimeout(a.wk),a.wk=null)},L6=function(a){a.g.oy()||a.Uh||a.g.Lo(a)},K6=function(a){O6(a);
g.af(a.Yo);a.Yo=null;a.l.stop();g.Vm(a.A);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.yf&&(a.yf=null)},J6=function(a,b){try{a.g.cC(a,b),a.g.qf(4)}catch(c){}},tBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;sBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){tBa(a,b,c,d,f)},f)})}},sBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{P6(d),c(!0)}catch(e){}};
d.onerror=function(){try{P6(d),c(!1)}catch(e){}};
d.onabort=function(){try{P6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{P6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},P6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},uBa=function(a){this.g=a;
this.l=new D6},vBa=function(a){var b=Q6(a.g,a.Bk,"/mail/images/cleardot.gif");
g6(b);tBa(b.toString(),5E3,(0,g.z)(a.TH,a),3,2E3);a.qf(1)},S6=function(a){var b=a.g.H;
if(null!=b)I6(5),b?(I6(11),R6(a.g,a,!1)):(I6(12),R6(a.g,a,!0));else if(a.we=new E6(a,void 0,void 0,void 0),a.we.ki=a.lr,b=a.g,b=Q6(b,b.Wl()?a.bl:null,a.pr),I6(5),!g.wd||g.rc(10))h6(b,"TYPE","xmlhttp"),F6(a.we,b,!1,a.bl,!1);else{h6(b,"TYPE","html");var c=a.we;a=!!a.bl;c.xj=3;c.kh=g6(b.clone());qBa(c,a)}},T6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new D6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},wBa=function(a,b){this.g=a;
this.map=b;this.context=null},xBa=function(a){g.cf.call(this,"statevent",a)},yBa=function(a,b){g.cf.call(this,"timingevent",a);
this.size=b},zBa=function(a){g.cf.call(this,"serverreachability",a)},CBa=function(a){ABa(a);
if(3==a.g){var b=a.Il++,c=a.Dn.clone();g.Im(c,"SID",a.o);g.Im(c,"RID",b);g.Im(c,"TYPE","terminate");U6(a,c);b=new E6(a,a.o,b,void 0);b.xj=2;b.kh=g6(c.clone());(new window.Image).src=b.kh;b.dk=(0,g.G)();G6(b)}BBa(a)},DBa=function(a){a.oI(1,0);
a.Dn=Q6(a,null,a.kr);V6(a)},ABa=function(a){a.Zg&&(a.Zg.abort(),a.Zg=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.qg&&(g.w.clearTimeout(a.qg),a.qg=null);W6(a);a.Wd&&(a.Wd.cancel(),a.Wd=null);a.bh&&(g.w.clearTimeout(a.bh),a.bh=null)},EBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new wBa(a.MO++,b));2!=a.g&&3!=a.g||V6(a)},V6=function(a){a.Wd||a.bh||(a.bh=N6((0,g.z)(a.hC,a),0),a.qj=0)},GBa=function(a,b){if(1==a.g){if(!b){a.Il=Math.floor(1E5*Math.random());
var c=a.Il++,d=new E6(a,"",c,void 0);d.ki=null;var e=X6(a),f=a.Dn.clone();g.Im(f,"RID",c);g.Im(f,"CVER","1");U6(a,f);lBa(d,f,e);a.Wd=d;a.g=2}}else 3==a.g&&(b?FBa(a,b):0==a.l.length||a.Wd||FBa(a))},FBa=function(a,b){if(b)if(6<a.Wh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Il-1;var d=X6(a)}else c=b.F,d=b.Ji;else c=a.Il++,d=X6(a);var e=a.Dn.clone();g.Im(e,"SID",a.o);g.Im(e,"RID",c);g.Im(e,"AID",a.Mj);U6(a,e);c=new E6(a,a.o,c,a.qj+1);c.ki=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Wd=c;lBa(c,e,d)},U6=function(a,b){if(a.sd){var c=a.sd.Tx();
c&&g.Kb(c,function(a,c){g.Im(b,c,a)})}},X6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Wh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Wh?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},HBa=function(a){a.wc||a.qg||(a.D=1,a.qg=N6((0,g.z)(a.gC,a),0),a.dj=0)},Y6=function(a){if(a.wc||a.qg||3<=a.dj)return!1;
a.D++;a.qg=N6((0,g.z)(a.gC,a),IBa(a,a.dj));a.dj++;return!0},R6=function(a,b,c){a.Hp=c;
a.Mf=b.yg;a.C||DBa(a)},W6=function(a){null!=a.Yh&&(g.w.clearTimeout(a.Yh),a.Yh=null)},IBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Z6=function(a,b){if(2==b||9==b){var c=null;
a.sd&&(c=null);var d=(0,g.z)(a.KU,a);c||(c=new g.zm("//www.google.com/images/cleardot.gif"),g6(c));sBa(c.toString(),1E4,d)}else I6(2);JBa(a,b)},JBa=function(a,b){a.g=0;
a.sd&&a.sd.Mw(b);BBa(a);ABa(a)},BBa=function(a){a.g=0;
a.Mf=-1;if(a.sd)if(0==a.A.length&&0==a.l.length)a.sd.yq();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.sd.yq(b)}},Q6=function(a,b,c){var d=g.Jm(c);
if(""!=d.l)b&&g.Bm(d,b+"."+d.l),g.Cm(d,d.B);else{var e=window.location;d=JAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Nk&&g.Kb(a.Nk,function(a,b){g.Im(d,b,a)});
g.Im(d,"VER",a.Wh);U6(a,d);return d},N6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},I6=function(a){$6.dispatchEvent(new xBa($6,a))},KBa=function(){},LBa=function(a,b){this.action=a;
this.params=b||{}},a7=function(a,b){g.L.call(this);
this.g=new g.Xt(this.MS,0,this);g.M(this,this.g);this.dd=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},b7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.RC;this.l=new a7(this.pV,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},MBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Hp,sessionId:a.g.o,arrayId:a.g.Mj}},NBa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&GBa(a.g),CBa(a.g));a.F=0},c7=function(a){return!!a.g&&3==a.g.g},OBa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},d7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Jg(a)||"";b&&(this.port=":"+b);this.domain=g.Ig(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},e7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Sg(c+b,{})},f7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Jb:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),yd:g.Fa(a.B,e)};c&&(a.Mb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.oE(b,a)},SBa=function(){var a=PBa;
QBa();g7.push(a);RBa(g7)},h7=function(a,b){QBa();
var c=g7,d=TBa(a,String(b));g.Qa(c)?UBa(d):(RBa(c),(0,g.B)(c,function(a){a(d)}))},QBa=function(){g7||(g7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",g7,void 0))},UBa=function(a){var b=(i7+1)%50;
i7=b;j7[b]=a;k7||(k7=49==b)},RBa=function(a){var b=j7;
if(b[0]){var c=i7,d=k7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
j7=Array(50);i7=-1;k7=!1}},TBa=function(a,b){var c=((0,g.G)()-VBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},l7=function(a){g.GF.call(this);
this.D=a;this.g=[]},WBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},XBa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Jd)(a.g,function(a){return!!o6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=WBa(a,b[d])||c;return c},YBa=function(a,b){var c=a.g.length;
a.g=(0,g.Jd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},m7=function(a,b,c,d){g.GF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.wa=window.NaN},o7=function(a){l7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;n7(this);this.info("Initializing with "+m6(this.g))},ZBa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=e7(a.o,"/pairing/get_lounge_token_batch");
f7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.WI,a),(0,g.z)(a.VI,a))}},n7=function(a){var b=RAa(XAa());
b=(0,g.Jd)(b,function(a){return!a.uuid});
return XBa(a,b)},p7=function(a,b){ZAa((0,g.H)(a.g,PAa));
b&&YAa()},r7=function(a,b){g.GF.call(this);
this.C=b;var c=g.NG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.C(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;q7("Initialized with "+g.zg(this.g))},$Ba=function(a,b,c){var d=e7(a.B,"/pairing/get_screen_availability");
f7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},s7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(q7("Updated online screens: "+g.zg(a.g)),a.g=b,a.R("screenChange"));aCa(a)},t7=function(a){(0,window.isNaN)(a.o)||g.TD(a.o);
a.o=g.RD((0,g.z)(a.ku,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},q7=function(a){h7("OnlineScreenService",a)},bCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},aCa=function(a){a=g.Sb(g.Lb(a.g,function(a){return a}));
g.ib(a);a.length?g.MG("yt-remote-online-screen-ids",a.join(","),60):g.OG("yt-remote-online-screen-ids")},u7=function(a){l7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};cCa(this)},eCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ne();if(k=(c?p6(k,c):null)||p6(k,b)){k.uuid=b;var l=v7(a,k);$Ba(a.l,l,function(a){e(a?l:null)})}else c?dCa(a,c,(0,g.z)(function(a){var f=v7(this,new j6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));$Ba(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},fCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},dCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Mb:{screen_ids:b},method:"POST",context:a,Jb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.oE(e7(a.C,"/pairing/get_lounge_token_batch"),e)},gCa=function(a){a.g=a.o.ne();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+m6(a.g))},cCa=function(a){w7(a);
a.o=new o7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.mJ,a));gCa(a);a.A=RAa(g.NG("yt-remote-automatic-screen-cache")||[]);w7(a);a.info("Initializing automatic screens: "+m6(a.A));a.l=new r7(a.C,(0,g.z)(a.ne,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},v7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=p6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.MG("yt-remote-automatic-screen-cache",(0,g.H)(a.A,PAa)));w7(a);a.B[b.uuid]=b.id;g.MG("yt-remote-device-id-map",a.B,31536E3);return b},w7=function(a){a.B=g.NG("yt-remote-device-id-map")||{}},x7=function(a,b,c){g.GF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},y7=function(a,b){h7(a.M,b)},z7=function(a,b){x7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.vV,this);this.B=(0,g.z)(this.yT,this);this.A=g.RD((0,g.z)(function(){hCa(this,null)},this),12E4)},iCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.zg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){y7(this,"Failed to send message: getMdxSessionStatus.")},a)):y7(a,"Sending yt message without session: "+g.zg(b))},hCa=function(a,b){g.TD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Mo,a),d=(0,g.z)(a.te,a);a.gy(b,c,d,5)}}else a.te(Error("Waiting for session status timed out."))},A7=function(a,b,c){x7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.yV,this);this.g=g.y},jCa=function(a){a.g=a.H.uE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Mo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.te(a)},a))},kCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}aBa()&&(b.env_useStageMdx=1);return g.Qg(b)},B7=function(a,b){x7.call(this,a,b,"ManualSession");
this.g=g.RD((0,g.z)(this.Nj,this,null),150)},C7=function(a,b,c,d){g.GF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.aS,this)},lCa=function(a,b){return b?g.Ma(a.o,function(a){return k6(b,a.label)},a):null},D7=function(a){h7("Controller",a)},PBa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},E7=function(a){return a.B||!!a.o.length||!!a.g},F7=function(a,b,c){b!=a.g&&(g.af(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.eC,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.Nj(null)):a.R("yt-remote-cast2-session-change",null))},mCa=function(a){var b=a.l.tE(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&k6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=lCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},sCa=function(a,b,c,d,e,f,k){nCa()?oCa(b,e,f,k)&&(H7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?pCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?pCa(a,c):(I7("Failed to load cast API: "+d),J7(!1),H7(!1),g.OG("yt-remote-cast-available"),g.OG("yt-remote-cast-receiver"),qCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):dBa():A6("CriOS")?iBa():A6("Android")&&A6("Chrome/")&&window.navigator.presentation?jBa():window.chrome&&window.navigator.presentation&&!A6("Edge")?(B6(),x6(rCa.map(gBa))):y6())):G7("Cannot initialize because not running Chrome")},qCa=function(){G7("dispose");
var a=K7();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);tCa(!1);g.TF(L7);L7.length=0},M7=function(){return!!g.NG("yt-remote-cast-installed")},uCa=function(){var a=g.NG("yt-remote-cast-receiver");
return a?a.friendlyName:null},vCa=function(){G7("clearCurrentReceiver");
g.OG("yt-remote-cast-receiver")},wCa=function(){return M7()?K7()?K7().getCastSession():(I7("getCastSelector: Cast is not initialized."),null):(I7("getCastSelector: Cast API is not installed!"),null)},O7=function(){M7()?K7()?N7()?(G7("Requesting cast selector."),K7().requestSession()):(G7("Wait for cast API to be ready to request the session."),L7.push(g.SF("yt-remote-cast2-api-ready",O7))):I7("requestCastSelector: Cast is not initialized."):I7("requestCastSelector: Cast API is not installed!")},P7=
function(a,b){N7()?K7().setConnectedScreenStatus(a,b):I7("setConnectedScreenStatus called before ready.")},nCa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.OJ||a},xCa=function(a,b){K7().init(a,b)},oCa=function(a,b,c,d){var e=!1;
K7()||(a=new C7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.MG("yt-remote-cast-available",a);g.WF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){G7("onReceiverSelected: "+a.friendlyName);
g.MG("yt-remote-cast-receiver",a);g.WF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){G7("onReceiverResumed: "+a.friendlyName);
g.MG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){G7("onSessionChange: "+l6(a));
a||g.OG("yt-remote-cast-receiver");g.WF("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
G7("cloudview.createSingleton_: "+e);return e},K7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},pCa=function(a,b){J7(!0);
H7(!1);xCa(a,function(a){a?(tCa(!0),g.VF("yt-remote-cast2-api-ready")):(I7("Failed to initialize cast API."),J7(!1),g.OG("yt-remote-cast-available"),g.OG("yt-remote-cast-receiver"),qCa());b(a)})},G7=function(a){h7("cloudview",a)},I7=function(a){h7("cloudview",a)},J7=function(a){G7("setCastInstalled_ "+a);
g.MG("yt-remote-cast-installed",a)},N7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},tCa=function(a){G7("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},H7=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},Q7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Pf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},R7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Pf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},S7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},T7=function(a,b){a.F=b;
a.D=(0,g.G)()},U7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},V7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&R7(a)},W7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.Pf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},Y7=function(a,b){g.GF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.hC;this.o=this.l=null;this.H=(0,g.z)(this.wP,this);this.D=(0,g.z)(this.Ll,this);this.F=(0,g.z)(this.vP,this);this.I=(0,g.z)(this.JP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.lv,this),yCa(this))):c=3;0!=c&&(b?this.lv(c):g.RD((0,g.z)(function(){this.lv(c)},this),0));
var d=wCa();d&&X7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},Z7=function(a){return new Q7(a.A.getPlayerContextData())},yCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.WR,a),this))},a)},zCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},$7=function(a,b){50>a.B.Fc()&&g.jC(a.B,b)},b8=function(a,b,c){var d=Z7(a);
T7(d,c);-1E3!=d.g&&(d.g=b);a8(a,d)},c8=function(a,b,c){a.A.sendMessage(b,c)},a8=function(a,b){zCa(a);
a.A.setPlayerContextData(W7(b));yCa(a)},X7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Ll(null));
a.o=b;a.o&&(h7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Ll(a.o.media[0]))},ACa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=Z7(a);b.contentId!=d.videoId&&h7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;T7(d,a.l.getEstimatedTime());a8(a,d)}else h7("CP","No cast media video. Ignoring state update.")},d8=function(a,b,c){return(0,g.z)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),c8(this,b,c))},a)},e8=function(a,b,c){g.GF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.P=[];this.A=this.D=this.o=this.Za=this.g=null;this.oa=a;this.P.push(g.qF(window,"beforeunload",(0,g.z)(this.LI,this)));this.l=[];this.Za=new Q7;this.X=b.id;this.g=BCa(this,c);this.g.subscribe("handlerOpened",this.AP,this);this.g.subscribe("handlerClosed",this.xP,this);this.g.subscribe("handlerError",this.yP,this);this.g.subscribe("handlerMessage",this.zP,this);OBa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.PG()&&g.MG("yt-remote-session-video-id",a)},this)},f8=function(a){h7("conn",a)},BCa=function(a,b){return new b7(e7(a.oa,"/bc"),b)},g8=function(a,b){a.R("proxyStateChange",b)},CCa=function(a){a.B=g.RD((0,g.z)(function(){f8("Connecting timeout");
this.C(1)},a),2E4)},h8=function(a){g.TD(a.B);
a.B=window.NaN},i8=function(a){g.TD(a.M);
a.M=window.NaN},DCa=function(a){j8(a);
a.K=g.RD((0,g.z)(function(){k8(this,"getNowPlaying")},a),2E4)},j8=function(a){g.TD(a.K);
a.K=window.NaN},FCa=function(a,b){b&&(h8(a),i8(a));
b==(c7(a.g)&&(0,window.isNaN)(a.B))?b&&(g8(a,1),k8(a,"getSubtitlesTrack")):b?(a.W()&&a.Za.reset(),g8(a,1),k8(a,"getNowPlaying"),ECa(a)):a.C(1)},GCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Yb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},HCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;V7(a.Za,c,d);a.R("remoteQueueChange")},JCa=function(a,b){b.params=b.params||{};
HCa(a,b);ICa(a,b);a.R("autoplayDismissed")},ICa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
T7(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?DCa(a):j8(a);
a.R("remotePlayerChange")},KCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);T7(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},LCa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},MCa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},NCa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Pf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},ECa=function(a){g.TD(a.I);
a.I=g.RD((0,g.z)(a.C,a,1),864E5)},k8=function(a,b,c){c?f8("Sending: action="+b+", params="+g.zg(c)):f8("Sending: action="+b);
a.g.sendMessage(b,c)},l8=function(a){l7.call(this,"ScreenServiceProxy");
this.cd=a;this.l=[];this.l.push(this.cd.$_s("screenChange",(0,g.z)(this.tV,this)));this.l.push(this.cd.$_s("onlineScreenChange",(0,g.z)(this.wR,this)))},SCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.LD("MDX_CONFIG")||b;TAa();t6();m8||(m8=new d7(b?b.loungeApiHost:void 0),aBa()&&(m8.g="/api/loungedev"));n8||(n8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",n8,void 0));OCa();var c=o8();if(!c){var d=new u7(m8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=o8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);sCa(a,d,function(a){a?p8()&&P7(p8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.WF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),q8("Initializing: "+g.zg(b)),r8.push(g.SF("yt-remote-cast2-availability-change",function(){g.WF("yt-remote-receiver-availability-change")})),r8.push(g.SF("yt-remote-cast2-receiver-selected",function(){s8(null);
g.WF("yt-remote-auto-connect","cast-selector-receiver")})),r8.push(g.SF("yt-remote-cast2-receiver-resumed",function(){g.WF("yt-remote-receiver-resumed","cast-selector-receiver")})),r8.push(g.SF("yt-remote-cast2-session-change",PCa)),r8.push(g.SF("yt-remote-connection-change",function(a){a?P7(p8(),"YouTube TV"):t8()||(P7(null,null),vCa())})),a=u8(),b.isAuto&&(a.id+="#dial"),g.MF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),q8(" -- with channel params: "+
g.zg(a)),QCa(a),c.start(),p8()||RCa())},UCa=function(){var a=TCa();
M7()&&g.NG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},TCa=function(){var a=o8().cd.$_gos();
var b=v8();b&&w8()&&(o6(a,b)||a.push(b));return SAa(a)},x8=function(){var a=VCa();
!a&&M7()&&uCa()&&(a={key:"cast-selector-receiver",name:uCa()});return a},VCa=function(){var a=TCa(),b=v8();
b||(b=t8());return g.Ma(a,function(a){return b&&k6(b,a.key)?!0:!1})},v8=function(){var a=p8();
if(!a)return null;var b=o8().ne();return p6(b,a)},PCa=function(a){q8("remote.onCastSessionChange_: "+l6(a));
if(a){var b=v8();b&&b.id==a.id?P7(b.id,"YouTube TV"):(b&&y8(),z8(a,1))}else w8()&&y8()},y8=function(){N7()?K7().stopSession():I7("stopSession called before API ready.");
var a=w8();a&&(a.disconnect(1),A8(null))},B8=function(){var a=w8();
return!!a&&3!=a.getProxyState()},q8=function(a){h7("remote",a)},o8=function(){if(!C8){var a=g.x("yt.mdx.remote.screenService_");
C8=a?new l8(a):null}return C8},p8=function(){return g.x("yt.mdx.remote.currentScreenId_")},WCa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},XCa=function(){return g.x("yt.mdx.remote.connectData_")},s8=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},w8=function(){return g.x("yt.mdx.remote.connection_")},A8=function(a){var b=w8();
s8(null);a||WCa("");g.wa("yt.mdx.remote.connection_",a,void 0);n8&&((0,g.B)(n8,function(b){b(a)}),n8.length=0);
b&&!a?g.WF("yt-remote-connection-change",!1):!b&&a&&g.WF("yt-remote-connection-change",!0)},t8=function(){var a=g.PG();
if(!a)return null;var b=o8().ne();return p6(b,a)},z8=function(a,b){v8()&&v8();
WCa(a.id);var c=new e8(m8,a,u8());c.connect(b,XCa());c.subscribe("beforeDisconnect",function(a){g.WF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){w8()&&A8(null)});
A8(c)},RCa=function(){var a=t8();
a?(q8("Resume connection to: "+l6(a)),z8(a,0)):(u6(),vCa(),q8("Skipping connecting because no session screen found."))},OCa=function(){var a=u8();
if(g.Yb(a)){a=s6();var b=g.NG("yt-remote-session-name")||"",c=g.NG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},u8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},QCa=function(a){a?(g.MG("yt-remote-session-app",a.app),g.MG("yt-remote-session-name",a.name)):(g.OG("yt-remote-session-app"),g.OG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},D8=function(a,b,c){g.L.call(this);
this.F=a;this.l=b;this.o=new g.DF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.PQ);this.o.O(b,"captionschanged",this.uP);this.o.O(b,"captionssettingschanged",this.BD);this.o.O(b,"videoplayerreset",this.No);this.o.O(b,"mdxautoplaycancel",this.SH);this.P=this.o.O(b,"onVolumeChange",this.OB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.bC,this);c.subscribe("remotePlayerChange",this.Ol,this);c.subscribe("remoteQueueChange",this.No,this);c.subscribe("autoplayUpNext",this.yB,
this);c.subscribe("previousNextChange",this.YB,this);c.subscribe("nowAutoplaying",this.QB,this);c.subscribe("autoplayDismissed",this.xB,this);this.suggestion=null;this.H=new g.VO(64);this.A=new g.Xt(this.xD,500,this);g.M(this,this.A);this.B=new g.Xt(this.yD,1E3,this);g.M(this,this.B);this.K=new C6(this.WU,0,this);g.M(this,this.K);this.C={};this.M=new g.Xt(this.eE,1E3,this);g.M(this,this.M);this.I=new g.Tk(this.zN,1E3,this);g.M(this,this.I);this.N=g.y;this.BD();this.No();this.Ol()},E8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},YCa=function(a){E8(a,0);
a.A.stop();F8(a,new g.VO(64))},H8=function(a,b){if(G8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Ci()},g.ec(c,b));a.g.pD(a.l.ea(1).videoId,c);a.C=Z7(a.g).l}},I8=function(a,b){var c=a.l.Zf();
if(c){var d=c.ie();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Ij;var m=Z7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};V7(m,k,l);g.t(b)&&(T7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);c8(c,"setPlaylist",q);e||a8(c,m);F8(a,new g.VO(1))},ZCa=function(a,b){if(b){var c=a.l.Ac("captions","tracklist",{bz:1});
c&&c.length?(a.l.Ld("captions","track",b),a.D=!1):(a.l.Qj("captions"),a.D=!0)}else a.l.Ld("captions","track",{})},G8=function(a){return Z7(a.g).videoId==a.l.ea(1).videoId},F8=function(a,b){a.B.stop();
var c=a.H;if(!g.cP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.YU(a.l,d);a.H=b;$Ca(a.F,c,b)}},J8=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.qoa()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.EV(this,250);g.M(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);aDa(this,g.VU(a))},aDa=function(a,b){if(3==a.o.Sa()){var c={RECEIVER_NAME:a.o.Ac("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},K8=function(a,b){g.MZ.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},L8=function(a){g.sV.call(this,a);
g.RG({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:n6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.VO(64);this.H=0;if(!g.zM(g.Y(this.g))){a=
this.g;var b=g.gI(a);b&&(b=b.uo())&&(b=new K8(a,b),g.M(this,b));b=new J8(a);g.M(this,b);g.mV(a,b.element,4)}},$Ca=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.iP(c,b))},M8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)y8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Zf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Ij,index:Math.max(a.g.dA(),0),currentTime:0==f?void 0:f}}else c=null;q8("Connecting to: "+g.zg(b));"cast-selector-receiver"==b.key?(s8(c||null),N7()?K7().setLaunchParams(c||null):I7("setLaunchParams called before ready.")):!c&&
B8()&&p8()==b.key?g.WF("yt-remote-connection-change",!0):(y8(),s8(c||null),c=o8().ne(),(c=p6(c,b.key))&&z8(c,1))}},pBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},M6={"'":"\\'"},bDa={},OAa={LW:"atp",d1:"ska",u0:"que",F_:"mus",Z0:"sus"};
i6.prototype.ln=function(){var a=new i6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var v6,r6="",z6=w6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",hBa=w6("loadCastFramework")||w6("loadCastApplicationFramework"),rCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(C6,g.L);g.h=C6.prototype;g.h.GI=function(a){this.A=arguments;this.g=!1;this.wa?this.o=(0,g.G)()+this.dd:this.wa=g.tg(this.B,this.dd)};
g.h.stop=function(){this.wa&&(g.ug(this.wa),this.wa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();C6.Z.V.call(this)};
g.h.HI=function(){this.o?(this.wa=g.tg(this.B,this.o-(0,g.G)()),this.o=null):(this.wa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};D6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
D6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=E6.prototype;g.h.ki=null;g.h.wf=!1;g.h.wk=null;g.h.ev=null;g.h.dk=null;g.h.xj=null;g.h.kh=null;g.h.Dh=null;g.h.Ji=null;g.h.Rc=null;g.h.gm=0;g.h.yf=null;g.h.Ip=null;g.h.lh=null;g.h.dl=-1;g.h.WC=!0;g.h.Uh=!1;g.h.qr=0;g.h.Yo=null;var nBa={},H6={};g.h=E6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.QT=function(a){a=a.target;var b=this.Yo;b&&3==g.hx(a)?b.vj():this.nE(a)};
g.h.nE=function(a){try{if(a==this.Rc)a:{var b=g.hx(this.Rc),c=this.Rc.l,d=this.Rc.getStatus();if(g.wd&&!g.rc(10)||g.yd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ef&&!g.nx(this.Rc))break a;this.Uh||4!=b||7==c||(8==c||0>=d?this.g.qf(3):this.g.qf(2));O6(this);var e=this.Rc.getStatus();this.dl=e;var f=g.nx(this.Rc);(this.wf=200==e)?(4==b&&K6(this),this.C?(oBa(this,b,f),g.ef&&this.wf&&3==b&&(this.A.T(this.l,"tick",this.LT),this.l.start())):J6(this,f),this.wf&&!this.Uh&&(4==b?this.g.Lo(this):
(this.wf=!1,G6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.lh=3,I6(13)):(this.lh=0,I6(14)),K6(this),L6(this))}}catch(k){this.Rc&&g.nx(this.Rc)}finally{}};
g.h.LT=function(){var a=g.hx(this.Rc),b=g.nx(this.Rc);this.gm<b.length&&(O6(this),oBa(this,a,b),this.wf&&4!=a&&G6(this))};
g.h.WS=function(a){N6((0,g.z)(this.VS,this,a),0)};
g.h.VS=function(a){this.Uh||(O6(this),J6(this,a),G6(this))};
g.h.jC=function(a){N6((0,g.z)(this.US,this,a),0)};
g.h.US=function(a){this.Uh||(K6(this),this.wf=a,this.g.Lo(this),this.g.qf(4))};
g.h.cancel=function(){this.Uh=!0;K6(this)};
g.h.nT=function(){this.wk=null;var a=(0,g.G)();0<=a-this.ev?(2!=this.xj&&this.g.qf(3),K6(this),this.lh=2,I6(18),L6(this)):rBa(this,this.ev-a)};g.h=uBa.prototype;g.h.lr=null;g.h.we=null;g.h.Zo=!1;g.h.qy=null;g.h.An=null;g.h.mr=null;g.h.pr=null;g.h.Me=null;g.h.yg=-1;g.h.bl=null;g.h.Bk=null;g.h.connect=function(a){this.pr=a;a=Q6(this.g,null,this.pr);I6(3);this.qy=(0,g.G)();var b=this.g.F;null!=b?(this.bl=b[0],(this.Bk=b[1])?(this.Me=1,vBa(this)):(this.Me=2,S6(this))):(h6(a,"MODE","init"),this.we=new E6(this,void 0,void 0,void 0),this.we.ki=this.lr,F6(this.we,a,!1,null,!0),this.Me=0)};
g.h.TH=function(a){if(a)this.Me=2,S6(this);else{I6(4);var b=this.g;b.Mf=b.Zg.yg;Z6(b,9)}a&&this.qf(2)};
g.h.Jq=function(a){return this.g.Jq(a)};
g.h.abort=function(){this.we&&(this.we.cancel(),this.we=null);this.yg=-1};
g.h.oy=function(){return!1};
g.h.cC=function(a,b){this.yg=a.dl;if(0==this.Me)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Mf=this.yg;Z6(c,2);return}this.bl=c[0];this.Bk=c[1]}else c=this.g,c.Mf=this.yg,Z6(c,2);else if(2==this.Me)if(this.Zo)I6(7),this.mr=(0,g.G)();else if("11111"==b){if(I6(6),this.Zo=!0,this.An=(0,g.G)(),c=this.An-this.qy,!g.wd||g.rc(10)||500>c)this.yg=200,this.we.cancel(),I6(12),R6(this.g,this,!0)}else I6(8),this.An=this.mr=(0,g.G)(),this.Zo=!1};
g.h.Lo=function(){this.yg=this.we.dl;if(this.we.wf)0==this.Me?this.Bk?(this.Me=1,vBa(this)):(this.Me=2,S6(this)):2==this.Me&&((!g.wd||g.rc(10)?!this.Zo:200>this.mr-this.An)?(I6(11),R6(this.g,this,!1)):(I6(12),R6(this.g,this,!0)));else{0==this.Me?I6(9):2==this.Me&&I6(10);var a=this.g;a.Mf=this.yg;Z6(a,2)}};
g.h.Wl=function(){return this.g.Wl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.qf=function(a){this.g.qf(a)};g.h=T6.prototype;g.h.Nk=null;g.h.Wd=null;g.h.wc=null;g.h.kr=null;g.h.Dn=null;g.h.Cw=null;g.h.Sn=null;g.h.Il=0;g.h.MO=0;g.h.sd=null;g.h.bh=null;g.h.qg=null;g.h.Yh=null;g.h.Zg=null;g.h.Hp=null;g.h.Mj=-1;g.h.pz=-1;g.h.Mf=-1;g.h.qj=0;g.h.dj=0;g.h.Wh=8;var $6=new g.Ef;g.A(xBa,g.cf);g.A(yBa,g.cf);g.A(zBa,g.cf);g.h=T6.prototype;g.h.connect=function(a,b,c,d,e){I6(0);this.kr=b;this.Nk=c||{};d&&g.t(e)&&(this.Nk.OSID=d,this.Nk.OAID=e);this.C?(N6((0,g.z)(this.Zw,this,a),100),DBa(this)):this.Zw(a)};
g.h.Zw=function(a){this.Zg=new uBa(this);this.Zg.lr=null;this.Zg.l=this.B;this.Zg.connect(a)};
g.h.oy=function(){return 0==this.g};
g.h.hC=function(a){this.bh=null;GBa(this,a)};
g.h.gC=function(){this.qg=null;this.wc=new E6(this,this.o,"rpc",this.D);this.wc.ki=null;this.wc.qr=0;var a=this.Cw.clone();g.Im(a,"RID","rpc");g.Im(a,"SID",this.o);g.Im(a,"CI",this.Hp?"0":"1");g.Im(a,"AID",this.Mj);U6(this,a);if(!g.wd||g.rc(10))g.Im(a,"TYPE","xmlhttp"),F6(this.wc,a,!0,this.Sn,!1);else{g.Im(a,"TYPE","html");var b=this.wc,c=!!this.Sn;b.xj=3;b.kh=g6(a.clone());qBa(b,c)}};
g.h.cC=function(a,b){if(0!=this.g&&(this.wc==a||this.Wd==a))if(this.Mf=a.dl,this.Wd==a&&3==this.g)if(7<this.Wh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.qg){if(this.wc)if(this.wc.dk+3E3<this.Wd.dk)W6(this),this.wc.cancel(),this.wc=null;else break a;Y6(this);I6(19)}}else this.pz=c[1],0<this.pz-this.Mj&&37500>c[2]&&this.Hp&&0==this.dj&&!this.Yh&&(this.Yh=N6((0,g.z)(this.pP,this),6E3));else Z6(this,11)}else b!=bDa.PX.g&&Z6(this,11);else if(this.wc==a&&
W6(this),!g.E(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Mj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Sn=e[2],e=e[3],null!=e?this.Wh=e:this.Wh=6,this.g=3,this.sd&&this.sd.Ow(),this.Cw=Q6(this,this.Wl()?this.Sn:null,this.kr),HBa(this)):"stop"==e[0]&&Z6(this,7):3==this.g&&("stop"==e[0]?Z6(this,7):"noop"!=e[0]&&this.sd&&this.sd.Nw(e),this.dj=0)}}};
g.h.pP=function(){null!=this.Yh&&(this.Yh=null,this.wc.cancel(),this.wc=null,Y6(this),I6(20))};
g.h.Lo=function(a){if(this.wc==a){W6(this);this.wc=null;var b=2}else if(this.Wd==a)this.Wd=null,b=1;else return;this.Mf=a.dl;if(0!=this.g)if(a.wf)1==b?(b=(0,g.G)()-a.dk,$6.dispatchEvent(new yBa($6,a.Ji?a.Ji.length:0,b,this.qj)),V6(this),this.A.length=0):HBa(this);else{var c=a.lh,d;if(!(d=3==c||7==c||0==c&&0<this.Mf)){if(d=1==b)this.Wd||this.bh||1==this.g||2<=this.qj?d=!1:(this.bh=N6((0,g.z)(this.hC,this,a),IBa(this,this.qj)),this.qj++,d=!0);d=!(d||2==b&&Y6(this))}if(d)switch(c){case 1:Z6(this,5);
break;case 4:Z6(this,10);break;case 3:Z6(this,6);break;case 7:Z6(this,12);break;default:Z6(this,2)}}};
g.h.oI=function(a){if(!g.C(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.KU=function(a){a?I6(2):(I6(1),JBa(this,8))};
g.h.Jq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.bx;a.F=!1;return a};
g.h.isActive=function(){return!!this.sd&&this.sd.isActive(this)};
g.h.qf=function(a){$6.dispatchEvent(new zBa($6,a))};
g.h.Wl=function(){return!(!g.wd||g.rc(10))};
g.h=KBa.prototype;g.h.Ow=function(){};
g.h.Nw=function(){};
g.h.Mw=function(){};
g.h.yq=function(){};
g.h.Tx=function(){return{}};
g.h.isActive=function(){return!0};g.A(a7,g.L);g.h=a7.prototype;g.h.MS=function(){this.dd=Math.min(3E5,2*this.dd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.dd+15E3*Math.random();g.Yt(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.dd=5E3};g.A(b7,KBa);g.h=b7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Od=function(a){return this.o.Od(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.af(this.o),NBa(this),g.af(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new T6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.sd=null);d.sd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Mj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):c7(this)&&EBa(this.g,c)};
g.h.Ow=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)EBa(this.g,a[b])}this.R("handlerOpened")};
g.h.Mw=function(a){var b=2==a&&401==this.g.Mf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.yq=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Tx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.Nw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),CBa(this.g)):this.R("handlerMessage",new LBa(a[0],a[1]))};
g.h.pV=function(){this.l.isActive();var a=this.g,b=0;a.wc&&b++;a.Wd&&b++;0!=b||this.connect(this.B,this.A)};d7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
d7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
d7.prototype.B=function(a){a(Error("request timed out"))};var VBa=(0,g.G)(),g7=null,j7=Array(50),i7=-1,k7=!1;g.A(l7,g.GF);l7.prototype.ne=function(){return this.g};
l7.prototype.contains=function(a){return!!o6(this.g,a)};
l7.prototype.get=function(a){return a?p6(this.g,a):null};
l7.prototype.info=function(a){h7(this.D,a)};g.A(m7,g.GF);var cDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=m7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.wa)&&this.sE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.wa)||(g.TD(this.wa),this.wa=window.NaN)};
g.h.V=function(){this.stop();m7.Z.V.call(this)};
g.h.sE=function(){this.wa=window.NaN;this.g=g.oE(e7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:this.B},timeout:5E3,Jb:(0,g.z)(this.rV,this),onError:(0,g.z)(this.qV,this),yd:(0,g.z)(this.sV,this)})};
g.h.rV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new j6(c))};
g.h.qV=function(a){this.g=null;a.status&&404==a.status?this.l>=cDa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=cDa[this.l],this.wa=g.RD((0,g.z)(this.sE,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.sV=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(o7,l7);g.h=o7.prototype;g.h.start=function(){n7(this)&&this.R("screenChange");!g.NG("yt-remote-lounge-token-expiration")&&ZBa(this);g.TD(this.l);this.l=g.RD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){n7(this);WBa(this,a);p7(this,!1);this.R("screenChange");b(a);a.token||ZBa(this)};
g.h.remove=function(a,b){var c=n7(this);YBa(this,a)&&(p7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Dp=function(a,b,c,d){var e=n7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,p7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.TD(this.l);o7.Z.V.call(this)};
g.h.WI=function(a){n7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}p7(this,!b);b&&h7(this.D,"Missed "+b+" lounge tokens.")};
g.h.VI=function(a){h7(this.D,"Requesting lounge tokens failed: "+a)};g.A(r7,g.GF);g.h=r7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.NG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?t7(this):(this.A=(0,g.G)()+3E5,g.MG("yt-remote-fast-check-period",this.A),this.ku())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){q7("Updating availability on schedule.");var a=this.C(),b=g.Lb(this.g,function(b,d){return b&&!!p6(a,d)},this);
s7(this,b)};
g.h.V=function(){g.TD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);r7.Z.V.call(this)};
g.h.ku=function(){g.TD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=bCa(this);if(g.Pb(a)){var b=e7(this.B,"/pairing/get_screen_availability");this.l=f7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.uS,this,a),(0,g.z)(this.tS,this))}else s7(this,{}),t7(this)};
g.h.uS=function(a,b){this.l=null;var c=g.Sb(bCa(this));if(g.jb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;s7(this,d);t7(this)}else this.hc("Changing Screen set during request."),this.ku()};
g.h.tS=function(a){this.hc("Screen availability failed: "+a);this.l=null;t7(this)};
g.h.hc=function(a){h7("OnlineScreenService",a)};g.A(u7,l7);g.h=u7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Dp=function(a,b,c,d){this.o.contains(a)?this.o.Dp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,h7(this.D,a),d(Error(a)))};
g.h.ne=function(a){return a?this.g:g.Wa(this.g,(0,g.Jd)(this.A,function(a){return!this.contains(a)},this))};
g.h.tE=function(){return(0,g.Jd)(this.ne(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.uE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new m7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.af(f);d(v7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.af(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.uV=function(a,b,c,d){g.oE(e7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:a},timeout:5E3,Jb:(0,g.z)(function(a,d){var e=new j6(d.screen||{});if(!e.name||fCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);fCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(v7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
yd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.af(this.o);g.af(this.l);u7.Z.V.call(this)};
g.h.mJ=function(){gCa(this);this.R("screenChange");this.l.update()};
u7.prototype.dispose=u7.prototype.dispose;g.A(x7,g.GF);g.h=x7.prototype;g.h.Mo=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.te=function(a){this.ha()||(a&&y7(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){h7(this.M,a)};
g.h.wE=function(){return null};
g.h.uu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){y7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.uu("");x7.Z.V.call(this)};g.A(z7,x7);g.h=z7.prototype;g.h.tu=function(a){if(this.g){if(this.g==a)return;y7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);iCa(this)};
g.h.Nj=function(a){this.info("launchWithParams no-op for Cast: "+g.zg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.te()},this),(0,g.z)(function(){this.te(Error("Failed to stop receiver app."))},this)):this.te(Error("Stopping cast device witout session."))};
g.h.uu=g.y;g.h.V=function(){this.info("disposeInternal");g.TD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;z7.Z.V.call(this)};
g.h.yT=function(a,b){if(!this.ha())if(b){var c=g.Ww(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.zg(c));switch(d){case "mdxSessionStatus":hCa(this,c.screenId);break;default:y7(this,"Unknown youtube message: "+d)}}else y7(this,"Unable to parse message.")}else y7(this,"No data in message.")};
g.h.gy=function(a,b,c,d){eCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(y7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.RD((0,g.z)(this.gy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.wE=function(){return this.g};
g.h.vV=function(a){this.ha()||a||(y7(this,"Cast session died."),this.te())};g.A(A7,x7);g.h=A7.prototype;g.h.tu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Nj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.TD(this.C);this.A?this.A.stop((0,g.z)(this.te,this,null),(0,g.z)(this.te,this,"Failed to stop DIAL device.")):this.te()};
g.h.V=function(){this.g();this.g=g.y;g.TD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;A7.Z.V.call(this)};
g.h.yV=function(a){this.ha()||a||(y7(this,"DIAL session died."),this.g(),this.g=g.y,this.te())};
g.h.Yr=function(a){this.I=n6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,kCa(this));a(b);jCa(this)}else this.D=(0,g.z)(function(){g.TD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,kCa(this));a(b);jCa(this)},this),this.C=g.RD((0,g.z)(function(){this.D()},this),100)};
g.h.AK=function(a,b,c){eCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Mo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Yr(b,c)},this),(0,g.z)(function(a){y7(this,"Failed to get DIAL screen: "+a);
this.Yr(b,c)},this))};g.A(B7,x7);B7.prototype.stop=function(){this.te()};
B7.prototype.tu=g.y;B7.prototype.Nj=function(){g.TD(this.g);this.g=window.NaN;var a=p6(this.H.ne(),this.l.label);a?this.Mo(a):this.te(Error("No such screen"))};
B7.prototype.V=function(){g.TD(this.g);this.g=window.NaN;B7.Z.V.call(this)};g.A(C7,g.GF);g.h=C7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.dC,this),(0,g.z)(this.eS,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.aQ,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),SBa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.vE,this)),this.o=mCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.hc("Failed to set initial custom receivers: "+g.zg(a))},this)),this.R("yt-remote-cast2-availability-change",E7(this)),b(!0))},this),(0,g.z)(function(a){this.hc("Failed to initialize API: "+g.zg(a));
b(!1)},this))};
g.h.tU=function(a,b){D7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)D7("Unsetting old screen status: "+this.g.l.friendlyName),F7(this,null)}if(a&&b){if(!this.g){c=p6(this.l.ne(),a);if(!c){D7("setConnectedScreenStatus: Unknown screen.");return}var d=lCa(this,c);d||(D7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.hc("Failed to set initial custom receivers: "+g.zg(a))},this)));
D7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);F7(this,new B7(this.l,d),!0)}this.g.uu(b)}else D7("setConnectedScreenStatus: no screen.")};
g.h.uU=function(a){this.ha()?this.hc("Setting connection data on disposed cast v2"):this.g?this.g.Nj(a):this.hc("Setting connection data without a session")};
g.h.xV=function(){this.ha()?this.hc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),F7(this,null)):D7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.dC,this),(0,g.z)(this.zS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.vE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],PBa);g.af(this.g);C7.Z.V.call(this)};
g.h.hc=function(a){h7("Controller",a)};
g.h.eC=function(a,b){this.g==a&&(b||F7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.aS=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),D7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)D7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{D7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:F7(this,
new B7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:F7(this,new A7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:F7(this,new z7(this.l,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.aQ=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return D7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);F7(this,new A7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.AK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Yr,b))};
g.h.dC=function(a){if(!this.ha()){D7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)D7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),F7(this,new z7(this.l,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=p6(this.l.ne(),c.label);
d&&k6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(D7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.af(this.g),this.g=new z7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.eC,this,this.g)),this.g.Nj(null));this.g.tu(a)}}};
g.h.wV=function(){return this.g?this.g.wE():null};
g.h.zS=function(a){this.ha()||(this.hc("Failed to estabilish a session: "+g.zg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&F7(this,null))};
g.h.eS=function(a){D7("Receiver availability updated: "+a);if(!this.ha()){var b=E7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;E7(this)!=b&&this.R("yt-remote-cast2-availability-change",E7(this))}};
g.h.vE=function(){this.ha()||(this.o=mCa(this),D7("Updating custom receivers: "+g.zg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.hc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",E7(this)))};
C7.prototype.setLaunchParams=C7.prototype.uU;C7.prototype.setConnectedScreenStatus=C7.prototype.tU;C7.prototype.stopSession=C7.prototype.xV;C7.prototype.getCastSession=C7.prototype.wV;C7.prototype.requestSession=C7.prototype.requestSession;C7.prototype.init=C7.prototype.init;C7.prototype.dispose=C7.prototype.dispose;var L7=[];g.h=Q7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";R7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Pf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+S7(this):this.H};
g.h.clone=function(){return new Q7(W7(this))};g.A(Y7,g.GF);g.h=Y7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,d8(this,"play")):c8(this,"play"),b8(this,1,U7(Z7(this))),this.R("remotePlayerChange")):$7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,d8(this,"pause")):c8(this,"pause"),b8(this,2,U7(Z7(this))),this.R("remotePlayerChange")):$7(this,this.pause)};
g.h.rE=function(a){if(1==this.g){if(this.l){var b=Z7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,d8(this,"seekTo",{newTime:a}))}else c8(this,"seekTo",{newTime:a});b8(this,3,a);this.R("remotePlayerChange")}else $7(this,g.Fa(this.rE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,d8(this,"stopVideo")):c8(this,"stopVideo");var a=Z7(this);a.index=-1;a.videoId="";R7(a);a8(this,a);this.R("remotePlayerChange")}else $7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=Z7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){h7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){h7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);c8(this,"setVolume",e)}c.muted=b;c.volume=a;a8(this,c)}else $7(this,g.Fa(this.setVolume,a,b))};
g.h.pD=function(a,b){if(1==this.g){var c=Z7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.zg(b.style),g.ec(d,c.l));c8(this,"setSubtitlesTrack",d);a8(this,c)}else $7(this,g.Fa(this.pD,a,b))};
g.h.kv=function(a,b){if(1==this.g){c8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Qb.id});var c=Z7(this);c.audioTrackId=b.Qb.id;a8(this,c)}else $7(this,g.Fa(this.kv,a,b))};
g.h.qE=function(a,b){if(1==this.g){if(a&&b){var c=Z7(this);V7(c,a,b);a8(this,c)}c8(this,"previous")}else $7(this,g.Fa(this.qE,a,b))};
g.h.pE=function(a,b){if(1==this.g){if(a&&b){var c=Z7(this);V7(c,a,b);a8(this,c)}c8(this,"next")}else $7(this,g.Fa(this.pE,a,b))};
g.h.yx=function(){1==this.g?c8(this,"dismissAutoplay"):$7(this,this.yx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}Y7.Z.dispose.call(this)};
g.h.V=function(){zCa(this);this.A=null;this.B.clear();X7(this,null);Y7.Z.V.call(this)};
g.h.lv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.kC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.WR=function(a,b){this.R(a,b)};
g.h.wP=function(a){if(!a)this.Ll(null),X7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=Z7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)h7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,a8(this,b)}};
g.h.Ll=function(a){h7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),ACa(this),this.R("remotePlayerChange")};
g.h.vP=function(a){a?(ACa(this),this.R("remotePlayerChange")):this.Ll(null)};
g.h.JP=function(){var a=wCa();a&&X7(this,a)};
g.h.hc=function(a){h7("CP",a)};g.A(e8,g.GF);g.h=e8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;T7(this.Za,m);this.A="UNSUPPORTED";f8("Connecting with setPlaylist and params: "+g.zg(l));this.g.connect({method:"setPlaylist",params:g.zg(l)},a,WAa())}else f8("Connecting without params"),
this.g.connect({},a,WAa());CCa(this)};
g.h.dispose=function(){this.ha()||(this.R("beforeDispose"),g8(this,3));e8.Z.dispose.call(this)};
g.h.V=function(){h8(this);j8(this);i8(this);g.TD(this.H);this.H=window.NaN;g.TD(this.I);this.I=window.NaN;this.o=null;g.rF(this.P);this.P.length=0;this.g.dispose();e8.Z.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.LI=function(){this.C(2)};
g.h.AP=function(){f8("Channel opened");this.N&&(this.N=!1,i8(this),this.M=g.RD((0,g.z)(function(){f8("Timing out waiting for a screen.");this.C(1)},this),15E3));
$Aa(MBa(this.g),this.X)};
g.h.xP=function(){f8("Channel closed");(0,window.isNaN)(this.B)?u6(!0):u6();this.dispose()};
g.h.yP=function(a){u6();(0,window.isNaN)(this.F())?(f8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,f8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),g8(this,2))};
g.h.zP=function(a){a.params?f8("Received: action="+a.action+", params="+g.zg(a.params)):f8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Ww(a.params.devices);this.l=(0,g.H)(a,function(a){return new i6(a)});
a=!!g.Ma(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
FCa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
FCa(this,!1);break;case "remoteConnected":var b=new i6(g.Ww(a.params.device));g.Ma(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new i6(g.Ww(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":HCa(this,a);break;case "nowPlaying":JCa(this,a);break;case "onStateChange":ICa(this,a);break;case "onAdStateChange":KCa(this,a);break;case "onVolumeChanged":LCa(this,a);break;case "onSubtitlesTrackChanged":GCa(this,a);break;case "nowAutoplaying":MCa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":NCa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:f8("Unrecognized action: "+a.action)}};
g.h.eU=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&k8(this,"getNowPlaying")}};
e8.prototype.subscribe=e8.prototype.subscribe;e8.prototype.unsubscribeByKey=e8.prototype.Od;e8.prototype.fa=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?c7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
e8.prototype.getProxyState=e8.prototype.fa;e8.prototype.C=function(a){f8("Disconnecting with "+a);h8(this);this.R("beforeDisconnect",a);1==a&&u6();NBa(this.g,a);this.dispose()};
e8.prototype.disconnect=e8.prototype.C;e8.prototype.da=function(){var a=this.Za;this.o&&(a=this.Za.clone(),V7(a,this.o,a.index));return W7(a)};
e8.prototype.getPlayerContextData=e8.prototype.da;
e8.prototype.ma=function(a){var b=new Q7(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.TD(this.H),this.H=g.RD((0,g.z)(this.eU,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&U7(this.Za)==U7(b)&&g.zg(this.Za.l)==g.zg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
e8.prototype.setPlayerContextData=e8.prototype.ma;e8.prototype.W=function(){var a=this.g.C.id,b=g.Ma(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
e8.prototype.getOtherConnectedRemoteId=e8.prototype.W;e8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
e8.prototype.getReconnectTimeout=e8.prototype.F;e8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
e8.prototype.getAutoplayMode=e8.prototype.Y;e8.prototype.ba=function(){return this.D||""};
e8.prototype.getAutoplayVideoId=e8.prototype.ba;e8.prototype.ra=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Zt(a.g);a.start()}};
e8.prototype.reconnect=e8.prototype.ra;e8.prototype.ia=function(a,b){k8(this,a,b);ECa(this)};
e8.prototype.sendMessage=e8.prototype.ia;g.A(l8,l7);g.h=l8.prototype;g.h.ne=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.add=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Dp=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.cd.$_ubk(this.l[a]);this.l.length=0;this.cd=null;l8.Z.V.call(this)};
g.h.tV=function(){this.R("screenChange")};
g.h.wR=function(){this.R("onlineScreenChange")};
u7.prototype.$_st=u7.prototype.start;u7.prototype.$_gspc=u7.prototype.uV;u7.prototype.$_gsppc=u7.prototype.uE;u7.prototype.$_c=u7.prototype.contains;u7.prototype.$_g=u7.prototype.get;u7.prototype.$_a=u7.prototype.add;u7.prototype.$_un=u7.prototype.Dp;u7.prototype.$_r=u7.prototype.remove;u7.prototype.$_gs=u7.prototype.ne;u7.prototype.$_gos=u7.prototype.tE;u7.prototype.$_s=u7.prototype.subscribe;u7.prototype.$_ubk=u7.prototype.Od;var m8=null,n8=null,C8=null,r8=[];g.p(D8,g.L);g.h=D8.prototype;
g.h.V=function(){g.L.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.bC,this);this.g.unsubscribe("remotePlayerChange",this.Ol,this);this.g.unsubscribe("remoteQueueChange",this.No,this);this.g.unsubscribe("autoplayUpNext",this.yB,this);this.g.unsubscribe("previousNextChange",this.YB,this);this.g.unsubscribe("nowAutoplaying",this.QB,this);this.g.unsubscribe("autoplayDismissed",this.xB,this);this.g=this.F=null};
g.h.zA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(G8(this)){if(!Z7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":Z7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.vj(c[0],c[1]);break;case "control_subtitles_set_track":H8(this,c[0]);break;case "control_set_audio_track":c=c[0],G8(this)&&this.g.kv(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();I8(this,0==c?void 0:c);break;case "control_seek":I8(this,c[0]);break;case "control_subtitles_set_track":H8(this,c[0]);break;case "control_set_audio_track":c=c[0],G8(this)&&this.g.kv(this.l.ea(1).videoId,c)}};
g.h.uP=function(a){this.K.GI(a)};
g.h.WU=function(a){this.zA("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.BD=function(){var a=this.l.Ac("captions","track");g.Yb(a)||H8(this,a)};
g.h.OB=function(a){if(G8(this)){this.g.unsubscribe("remotePlayerChange",this.Ol,this);var b=Math.round(a.volume);a=!!a.muted;var c=Z7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Ol,this)}};
g.h.PQ=function(){g.Yb(this.C)||ZCa(this,this.C);this.D=!1};
g.h.bC=function(a,b){this.B.stop();2==b&&this.yD()};
g.h.Ol=function(){if(G8(this)){this.A.stop();var a=Z7(this.g);switch(a.g){case 1081:case 1:F8(this,new g.VO(8));this.xD();break;case 1085:case 3:F8(this,new g.VO(9));break;case 1083:case 0:F8(this,new g.VO(2));this.I.stop();E8(this,this.l.ea().lengthSeconds);break;case 1084:F8(this,new g.VO(4));break;case 2:F8(this,new g.VO(4));E8(this,U7(a));break;case -1:F8(this,new g.VO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},F8(this,new g.VO(128,a))}a=Z7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,ZCa(this,a));a=Z7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.eE()}else YCa(this)};
g.h.YB=function(){this.l.R("mdxpreviousnextchange")};
g.h.No=function(){G8(this)||YCa(this)};
g.h.SH=function(){this.g.yx()};
g.h.yB=function(a){a&&(a=g.oE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.z)(this.ZS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.ZS=function(a,b){var c=new g.VN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.QB=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.xB=function(){this.l.R("mdxautoplaycanceled")};
g.h.zN=function(a,b){-1==Z7(this.g).g?I8(this,a):b&&this.g.rE(a)};
g.h.eE=function(){if(G8(this)){var a=Z7(this.g);this.o.Ba(this.P);a.muted?this.l.mute():this.l.ag();this.l.setVolume(a.volume);this.P=this.o.O(this.l,"onVolumeChange",this.OB)}};
g.h.xD=function(){this.A.stop();if(!this.g.ha()){var a=Z7(this.g);a.kb()&&F8(this,new g.VO(8));E8(this,U7(a));this.A.start()}};
g.h.yD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(J8,g.W);J8.prototype.A=function(a){aDa(this,a.state)};g.p(K8,g.MZ);K8.prototype.I=function(){var a=this.l.Ac("remote","receivers");a&&1<a.length&&!this.l.Ac("remote","quickCast")?(this.F=g.lb(a,this.B,this),g.NZ(this,(0,g.H)(a,this.B)),a=this.l.Ac("remote","currentReceiver"),this.pf(this.B(a)),this.enable(!0)):this.enable(!1)};
K8.prototype.B=function(a){return a.key};
K8.prototype.nf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
K8.prototype.wd=function(a){g.MZ.prototype.wd.call(this,a);this.l.Ld("remote","currentReceiver",this.F[a]);this.A.Rb()};g.p(L8,g.sV);g.h=L8.prototype;g.h.create=function(){SCa(g.mM(g.Y(this.g)));this.C.push(g.SF("yt-remote-before-disconnect",this.qP,this));this.C.push(g.SF("yt-remote-connection-change",this.fS,this));this.C.push(g.SF("yt-remote-receiver-availability-change",this.ZB,this));this.C.push(g.SF("yt-remote-auto-connect",this.dS,this));this.C.push(g.SF("yt-remote-receiver-resumed",this.cS,this));this.ZB()};
g.h.load=function(){this.g.Ys();g.sV.prototype.load.call(this);this.B=new D8(this,this.g,this.l);var a=(a=XCa())?a.currentTime:0;var b=B8()?new Y7(w8(),void 0):null;0==a&&b&&(a=U7(Z7(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));$Ca(this,this.D,this.D);g.Y_(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.bf(this.B,this.l);this.l=this.B=null;g.sV.prototype.unload.call(this);g.Y_(this.g.app,5)};
g.h.V=function(){g.TF(this.C);g.sV.prototype.V.call(this)};
g.h.Dl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.zA.apply(this.B,[a].concat(g.qa(c)))};
g.h.CI=function(){return this.loaded?this.B.suggestion:null};
g.h.Pf=function(){return this.l?Z7(this.l).Pf:!1};
g.h.hasNext=function(){return this.l?Z7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.nN=function(){var a=Z7(this.l),b=this.g.ea();return{allowSeeking:this.g.fd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+S7(a):a.A,isPeggedToLive:1>=(a.C?a.o+S7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+S7(a):a.o,seekableStart:0<a.B?a.B+S7(a):a.B}};
g.h.oN=function(){this.l&&this.l.pE()};
g.h.pN=function(){this.l&&this.l.qE()};
g.h.qP=function(a){1==a&&(this.I=this.l?Z7(this.l):null)};
g.h.fS=function(){var a=B8()?new Y7(w8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.af(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.bA(a.videoId,U7(a)));this.g.R("videodatachange","newdata",this.g.ea(),3)};
g.h.ZB=function(){this.F=[this.o].concat(UCa());var a=x8()||this.o;M8(this,a);this.g.ua("onMdxReceiversChange")};
g.h.dS=function(){var a=x8();M8(this,a)};
g.h.cS=function(){this.A=x8()};
g.h.mN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?O7():M8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&O7(),!0):!1}};
g.h.qN=function(){c8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Qc=function(){return!1};g.gY.remote=L8;})(_yt_player);
